const express=require('express')

const student=[{
    "id": 1,
    "first_name": "Jane",
    "last_name": "Sales",
    "email": "jsales0@mashable.com"
  }, {
    "id": 2,
    "first_name": "Carmella",
    "last_name": "Speare",
    "email": "cspeare1@sciencedaily.com"
  }, {
    "id": 3,
    "first_name": "Berty",
    "last_name": "Kuzemka",
    "email": "bkuzemka2@statcounter.com"
  }, {
    "id": 4,
    "first_name": "Gina",
    "last_name": "Jerrand",
    "email": "gjerrand3@yellowpages.com"
  }, {
    "id": 5,
    "first_name": "Earvin",
    "last_name": "Corson",
    "email": "ecorson4@imageshack.us"
  }, {
    "id": 6,
    "first_name": "Dacia",
    "last_name": "Brunroth",
    "email": "dbrunroth5@xing.com"
  }, {
    "id": 7,
    "first_name": "Sephira",
    "last_name": "Crilley",
    "email": "scrilley6@sfgate.com"
  }, {
    "id": 8,
    "first_name": "Felipa",
    "last_name": "Parmley",
    "email": "fparmley7@webmd.com"
  }, {
    "id": 9,
    "first_name": "Si",
    "last_name": "Mulbery",
    "email": "smulbery8@chicagotribune.com"
  }, {
    "id": 10,
    "first_name": "Ogdon",
    "last_name": "Denziloe",
    "email": "odenziloe9@feedburner.com"
  }]

  module.exports=student